### ISSUE TITLE
[Feat] 날씨앱 메인화면 구현

### ISSUE THREAD

**Issue by mini-min** [mini-min/Mini-Study-iOS#25]
## 👀 이슈 (issue)

날씨앱의 기본 메인 화면 기능을 구현합니다.

## 🚀 to-do

- [ ] 프로젝트 기본 세팅 (폰트, 에셋, 익스텐션, 네트워킹)
- [ ] MainVC 기본 레이아웃 
- [ ] 서버 통신 연결
- [ ] SearchBar 기능 구현
